//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_DisHekimligi.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIHAZ
    {
        public int CIHAZ_ID { get; set; }
        public string CIHAZ_AD { get; set; }
        public string ISLEM_BILGISI { get; set; }
        public Nullable<int> BIRIM_FIYAT { get; set; }
        public string SUTUN_AD { get; set; }
        public Nullable<int> SUTUN_ICERIK { get; set; }
        public Nullable<int> TOPLAM_FIYAT { get; set; }
    }
}
