//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_DisHekimligi.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosya
    {
        public int Dosya_ID { get; set; }
        public string Dosya_Ad { get; set; }
        public string Dosya_Tarih { get; set; }
        public byte[] Dosya_Icerik { get; set; }
    }
}
