//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_DisHekimligi.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        public int KUL_ID { get; set; }
        public string KUL_AD { get; set; }
        public string KUL_SIFRE { get; set; }
        public string AD_SOYAD { get; set; }
    }
}
